-- MySQL Script generated by MySQL Workbench
-- Wed Sep 23 11:26:41 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Enterprise_Gym
-- -----------------------------------------------------
-- Schema used for Group 5 Enterprise Gym database

-- -----------------------------------------------------
-- Schema Enterprise_Gym
--
-- Schema used for Group 5 Enterprise Gym database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Enterprise_Gym` ;
USE `Enterprise_Gym` ;

-- -----------------------------------------------------
-- Table `Enterprise_Gym`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enterprise_Gym`.`account` (
  `idaccount` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(200) NOT NULL,
  `password` VARCHAR(500) NOT NULL,
  `salt` VARCHAR(1000) NULL,
  `date_joined` DATE NOT NULL,
  `date_active` DATE NULL,
  PRIMARY KEY (`idaccount`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Enterprise_Gym`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enterprise_Gym`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(6) NOT NULL,
  `country` VARCHAR(45) NULL,
  `university` VARCHAR(45) NULL,
  `school` VARCHAR(45) NULL,
  `subject` VARCHAR(45) NULL,
  `year` YEAR NULL,
  `email` VARCHAR(45) NULL,
  `account_idaccount` INT UNSIGNED NOT NULL,
  `matriculation` INT NULL,
  `action_points` INT NOT NULL DEFAULT 0,
  `practice_points` INT NULL DEFAULT 0,
  `virtual_points` INT NULL DEFAULT 0,
  `project_points` INT NULL DEFAULT 0,
  `theory_points` INT NULL DEFAULT 0,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC),
  INDEX `fk_user_account1_idx` (`account_idaccount` ASC),
  CONSTRAINT `fk_user_account1`
    FOREIGN KEY (`account_idaccount`)
    REFERENCES `Enterprise_Gym`.`account` (`idaccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Enterprise_Gym`.`theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enterprise_Gym`.`theme` (
  `idtheme` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `points` INT NOT NULL,
  PRIMARY KEY (`idtheme`),
  UNIQUE INDEX `idtheme_UNIQUE` (`idtheme` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Enterprise_Gym`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enterprise_Gym`.`event` (
  `idevent` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(1000) NULL,
  `date` DATE NULL,
  `eventcol` INT NULL,
  `theme_idtheme` INT NOT NULL,
  `image` LONGBLOB NULL,
  `location` VARCHAR(45) NULL,
  `image_type` VARCHAR(45) NULL,
  `image_length` INT NULL,
  PRIMARY KEY (`idevent`),
  UNIQUE INDEX `idevent_UNIQUE` (`idevent` ASC),
  INDEX `fk_event_theme_idx` (`theme_idtheme` ASC),
  CONSTRAINT `fk_event_theme`
    FOREIGN KEY (`theme_idtheme`)
    REFERENCES `Enterprise_Gym`.`theme` (`idtheme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Enterprise_Gym`.`newsItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enterprise_Gym`.`newsItem` (
  `idnewsItem` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `story` VARCHAR(1000) NULL,
  `image` LONGBLOB NULL,
  `event_idevent` INT NOT NULL,
  `image_type` VARCHAR(45) NULL,
  `image_length` INT NULL,
  `dateAdded` DATE NOT NULL,
  `event_idevent` INT NULL,
  PRIMARY KEY (`idnewsItem`),
  UNIQUE INDEX `idnewsItem_UNIQUE` (`idnewsItem` ASC),
  INDEX `fk_newsItem_event1_idx` (`event_idevent` ASC),
  CONSTRAINT `fk_newsItem_event1`
    FOREIGN KEY (`event_idevent`)
    REFERENCES `Enterprise_Gym`.`event` (`idevent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Enterprise_Gym`.`event_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enterprise_Gym`.`event_has_user` (
  `event_idevent` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `attended` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`event_idevent`, `user_iduser`),
  INDEX `fk_event_has_user_user1_idx` (`user_iduser` ASC),
  INDEX `fk_event_has_user_event1_idx` (`event_idevent` ASC),
  CONSTRAINT `fk_event_has_user_event1`
    FOREIGN KEY (`event_idevent`)
    REFERENCES `Enterprise_Gym`.`event` (`idevent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_has_user_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `Enterprise_Gym`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Enterprise_Gym`.`accessToken`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enterprise_Gym`.`accessToken` (
  `idaccessToken` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`idaccessToken`),
  UNIQUE INDEX `idaccessToken_UNIQUE` (`idaccessToken` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Enterprise_Gym`.`Quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enterprise_Gym`.`Quiz` (
  `idQuiz` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `points` INT UNSIGNED NULL,
  PRIMARY KEY (`idQuiz`),
  UNIQUE INDEX `idQuiz_UNIQUE` (`idQuiz` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Enterprise_Gym`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enterprise_Gym`.`Question` (
  `idQuestion` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(500) NOT NULL,
  `number` INT UNSIGNED NOT NULL,
  `answerOne` VARCHAR(500) NOT NULL,
  `answerTwo` VARCHAR(500) NOT NULL,
  `answerThree` VARCHAR(500) NOT NULL,
  `answerFour` VARCHAR(500) NOT NULL,
  `correctAnswer` INT NOT NULL,
  `Quiz_idQuiz` INT NOT NULL,
  PRIMARY KEY (`idQuestion`),
  UNIQUE INDEX `idQuestion_UNIQUE` (`idQuestion` ASC),
  INDEX `fk_Question_Quiz1_idx` (`Quiz_idQuiz` ASC),
  CONSTRAINT `fk_Question_Quiz1`
    FOREIGN KEY (`Quiz_idQuiz`)
    REFERENCES `Enterprise_Gym`.`Quiz` (`idQuiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Enterprise_Gym`.`accessToken_has_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enterprise_Gym`.`accessToken_has_account` (
  `accessToken_idaccessToken` INT NOT NULL,
  `account_idaccount` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`accessToken_idaccessToken`, `account_idaccount`),
  INDEX `fk_accessToken_has_account_account1_idx` (`account_idaccount` ASC),
  INDEX `fk_accessToken_has_account_accessToken1_idx` (`accessToken_idaccessToken` ASC),
  CONSTRAINT `fk_accessToken_has_account_accessToken1`
    FOREIGN KEY (`accessToken_idaccessToken`)
    REFERENCES `Enterprise_Gym`.`accessToken` (`idaccessToken`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accessToken_has_account_account1`
    FOREIGN KEY (`account_idaccount`)
    REFERENCES `Enterprise_Gym`.`account` (`idaccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
